apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejsapi
  labels:
    app: nodejsapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejsapi
  template:
    metadata:
      labels:
        app: nodejsapi
    spec:
      containers:
        - name: nodejsapi-8000
          image: wjdguswn1203/nodejsapi
          ports:
            - containerPort: 8000
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: nodejs-secret
                  key: DB_HOST
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: nodejs-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nodejs-secret
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: nodejs-secret
                  key: DB_NAME
            - name: WCL_URL
              valueFrom:
                secretKeyRef:
                  name: nodejs-secret
                  key: WCL_URL
            - name: WCS_API_KEY
              valueFrom:
                secretKeyRef:
                  name: nodejs-secret
                  key: WCS_API_KEY
            - name: HUGGINGFACE_APIKEY
              valueFrom:
                secretKeyRef:
                  name: nodejs-secret
                  key: HUGGINGFACE_APIKEY
        - name: nodejsapi-8500
          image: raminicano/nodejsapi
          ports:
            - containerPort: 8500
          env:
            - name: FASTAPI_URL
              valueFrom:
                secretKeyRef:
                  name: nodejs-secret
                  key: FASTAPI_URL
            - name: NODE_URL1
              valueFrom:
                secretKeyRef:
                  name: nodejs-secret
                  key: NODE_URL1
            - name: NODE_URL2
              valueFrom:
                secretKeyRef:
                  name: nodejs-secret
                  key: NODE_URL2
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: nodejs-secret
                  key: PORT
