apiVersion: v1
kind: Service
metadata:
  name: nodejsapi
  labels:
    run: nodejsapi
spec:
  type: NodePort
  ports:
    - nodePort: 30007
      port: 8000
      targetPort: 8000
      protocol: TCP
      name: http-8000
    - nodePort: 30008
      port: 8500
      targetPort: 8500
      protocol: TCP
      name: http-8500
  selector:
    app: nodejsapi
  externalIPs:
    - 43.203.202.118
