apiVersion: v1
kind: Service
metadata:
  name: nodejsapi-service
spec:
  selector:
    app: nodejsapi
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      name: http-8000
    - protocol: TCP
      port: 8500
      targetPort: 8500
      name: http-8500
  type: LoadBalancer